### ISSUE TITLE
Error on docker build

### ISSUE THREAD

**Issue by tusharm** [faisyl/alpine-runit#2]
Hi,

It seems like the runit package is not available anymore in the repo. I get this error when  running Docker build:

```
Step 5 : RUN apk add runit
 ---> Running in 2617fb3ed645
ERROR: unsatisfiable constraints:
  runit (missing):
    required by: world[runit]
```

Tx

**Comment by faisyl** [comment]
I've updated the docker file to track community instead of testing. That
fixes it for now. I'll try and track down what caused this.

~faisal
